### ISSUE TITLE
Feature Request: Check if map platform exists

### ISSUE THREAD

**Issue by chitgoks** [SupasinTatiyanupanwong/map-kit-android#11]
Rather than the code throwing an exception, how about adding an if condition check so we can customize our own actions for it.

**Comment by SupasinTatiyanupanwong** [comment]
Initially I was planned to have it changeable at runtime but that probably don't have a good use case for it and such never get materialized.

Do you have anything in your mind now?  In addition to adding new API for availablity checks, I'm thinking between no-op implementation instead of crashing the app or providing a way for API hook so that the client can still make use of the map functionalities on their own. What do you think?

**Comment by chitgoks** [comment]
if theres a way not to crash the app, the better. i was thinking a true/false method. if theres no map, i show a prompt and then quit the app

**Comment by chitgoks** [comment]
Up

**Comment by chitgoks** [comment]
Up. By the way, your email does not exist anymore.

**Comment by SupasinTatiyanupanwong** [comment]
Hmm, seems like I forgot to continue my domain renewal.

Thanks for letting me know! Quite busy these days.

Sorry for the delay, tho.

**Comment by chitgoks** [comment]
its ok. i was worried the project might be abandoned 😅

yours  is a great lib

**Comment by SupasinTatiyanupanwong** [comment]
> Hi, seconding this. The nextbike app uses this lib, and crashes on my phone, which has neither of the supported map providers. This is especially sad, as i dont need the map in this app.
> 
> So, i would prefer the no op solution, to make the app compatible with my phone.

I'm working on it now, will release shortly.

**Comment by SupasinTatiyanupanwong** [comment]
The check is now available with `MapKit#isMapsOperational()` since 2.2.0.
